2020/11/19 12:16:55 [error] 28#28: *169 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 12:16:55 [error] 28#28: *169 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 12:16:55 [error] 28#28: *169 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:26:50 [error] 30#30: *63 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.3:8000/favicon.ico", host: "localhost", referrer: "http://localhost/admin/"
2020/11/19 16:26:54 [error] 30#30: *76 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:26:54 [error] 30#30: *76 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.3:8000/favicon.ico", host: "localhost", referrer: "http://localhost/admin/"
2020/11/19 16:26:56 [error] 30#30: *79 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:26:56 [error] 30#30: *79 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.3:8000/favicon.ico", host: "localhost", referrer: "http://localhost/admin/"
2020/11/19 16:26:56 [error] 30#30: *82 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:26:56 [error] 30#30: *82 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.3:8000/favicon.ico", host: "localhost", referrer: "http://localhost/admin/"
2020/11/19 16:26:56 [error] 30#30: *85 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:26:56 [error] 30#30: *85 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.3:8000/favicon.ico", host: "localhost", referrer: "http://localhost/admin/"
2020/11/19 16:26:57 [error] 30#30: *88 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:26:57 [error] 30#30: *88 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.3:8000/favicon.ico", host: "localhost", referrer: "http://localhost/admin/"
2020/11/19 16:26:57 [error] 30#30: *91 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:26:57 [error] 30#30: *91 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.3:8000/favicon.ico", host: "localhost", referrer: "http://localhost/admin/"
2020/11/19 16:26:57 [error] 30#30: *94 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:26:57 [error] 30#30: *94 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.3:8000/favicon.ico", host: "localhost", referrer: "http://localhost/admin/"
2020/11/19 16:26:59 [error] 30#30: *97 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:26:59 [error] 30#30: *97 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.3:8000/favicon.ico", host: "localhost", referrer: "http://localhost/admin/"
2020/11/19 16:26:59 [error] 30#30: *100 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:26:59 [error] 30#30: *100 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.3:8000/favicon.ico", host: "localhost", referrer: "http://localhost/admin/"
2020/11/19 16:27:00 [error] 30#30: *103 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:27:00 [error] 30#30: *103 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.3:8000/favicon.ico", host: "localhost", referrer: "http://localhost/admin/"
2020/11/19 16:27:00 [error] 30#30: *106 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:27:00 [error] 30#30: *106 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.3:8000/favicon.ico", host: "localhost", referrer: "http://localhost/admin/"
2020/11/19 16:27:00 [error] 30#30: *109 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:27:00 [error] 30#30: *109 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.3:8000/favicon.ico", host: "localhost", referrer: "http://localhost/admin/"
2020/11/19 16:27:00 [error] 30#30: *112 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:27:00 [error] 30#30: *112 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.3:8000/favicon.ico", host: "localhost", referrer: "http://localhost/admin/"
2020/11/19 16:27:01 [error] 30#30: *112 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:27:01 [error] 30#30: *112 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:27:02 [error] 30#30: *112 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:27:02 [error] 30#30: *112 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:27:02 [error] 30#30: *112 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:27:02 [error] 30#30: *112 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:27:02 [error] 30#30: *112 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:27:02 [error] 30#30: *112 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:27:03 [error] 30#30: *112 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:27:03 [error] 30#30: *112 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:27:03 [error] 30#30: *112 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:27:03 [error] 30#30: *112 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:27:03 [error] 30#30: *112 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:27:03 [error] 30#30: *112 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:27:04 [error] 30#30: *112 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:38:37 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:38:38 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:38:38 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:38:38 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:38:38 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:38:40 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:38:40 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:38:40 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:38:40 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:38:41 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:38:41 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:38:41 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:38:42 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:38:42 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:38:42 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:38:43 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:38:43 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:38:43 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:38:43 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:38:44 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:38:45 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:38:45 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:38:45 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:38:45 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:39:32 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
2020/11/19 16:42:07 [error] 29#29: *27 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: django_celery, request: "GET /admin/ HTTP/1.1", upstream: "http://172.18.0.3:8000/admin/", host: "localhost"
